[project]
name = "ac-materialization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.3",
    "microviewer>=1.13.1",
    "tensorstore>=0.1.75",
]
